### ISSUE TITLE
What does `add over margins` and `subset` args mean?

### ISSUE THREAD

**Issue by bsuwal** [uscensusbureau/census2020-das-e2e#6]
Hi, 

What does the parameter `add_over_margin` do, in the `Query` class? For eg. this is an example of it being used:
https://github.com/uscensusbureau/census2020-das-e2e/blob/d9faabf3de987b890a5079b914f5aba597215b14/programs/engine/cenquery.py#L131

 It is described in the docstring but I couldn't really understand it.

Where the parameter is set:
https://github.com/uscensusbureau/census2020-das-e2e/blob/d9faabf3de987b890a5079b914f5aba597215b14/programs/reader/invariants1940.py#L38

Relatedly, how does the `subset` parameter work?

**Comment by garfi303** [comment]
`add_over_margins` is used to marginalize out some target dimensions of the query. It is basically just a use of numpy.sum (https://numpy.org/doc/stable/reference/generated/numpy.sum.html) with some specified target axes. The axes indicated will be removed, reducing the number of dimensions in the resulting numpy.ndarray representation of the query by summing over them. To re-use one of numpy's own examples, if we have a 2x2 query that evaluates to `[[0, 1], [0, 5]]` then we can use add_over_margins with axis=1 to express that we want to remove the second dimension to get:

```
>>> np.sum([[0, 1], [0, 5]], axis=0)
array([0, 6])
```

In the specific case that buswal identified, add_over_margins is being used to implement the tot invariant:

```
add_over_margins = (0, 1, 2, 3)
```

https://github.com/uscensusbureau/census2020-das-e2e/blob/d9faabf3de987b890a5079b914f5aba597215b14/programs/reader/invariants1940.py#L38

where we note that the "raw" (i.e., without disclosure avoidance applied / unperturbed) persons histogram is used as this invariant's input data structure:

```
data = self.raw
```

https://github.com/uscensusbureau/census2020-das-e2e/blob/d9faabf3de987b890a5079b914f5aba597215b14/programs/reader/invariants1940.py#L37

In the e2e 1940 config file, we see that there are exactly 4 dimensions in the 1940 persons histogram schema:

```
PersonData.histogram: hhgq age18plus hispanic race
```

https://github.com/uscensusbureau/census2020-das-e2e/blob/d9faabf3de987b890a5079b914f5aba597215b14/E2E_1940_CONFIG.ini#L53

Identifying these with the axis numbers 0, 1, 2, 3, we see that the tot invariant is just taking the full hhgq * age18plus * hispanic * race histogram in each geographic unit and reducing it to a single number by summation -- i.e.,  the tot invariant is formulating a query which computes the total population for whichever geounit is currently relevant.

Subset serves a similar organizational role, but lets us express that we sometimes do not want to retain all levels of a variable (or all tuples of Cartesian products of variable levels). For example, subset is used here:

```
subset = (range(1, 8),)
```

https://github.com/uscensusbureau/census2020-das-e2e/blob/d9faabf3de987b890a5079b914f5aba597215b14/programs/reader/invariants1940.py#L60

to compute the gq_vect invariant by only retaining levels 1, 2, ...,7 of the first variable in the schema for the relevant numpy.ndarray. While the persons histogram had a schema defined by the 4 variables we examined previously, this invariant instead uses the raw_housing as its input representation:

```
data = self.raw_housing
```

This corresponds to a histogram with a simple, univariate schema, given by:

```
unit_dim = (9,)  # added one level to hhgq for vacant units
```

https://github.com/uscensusbureau/census2020-das-e2e/blob/d9faabf3de987b890a5079b914f5aba597215b14/programs/reader/e2e_1940_reader.py#L260

So, gq_vect is using subset to drop the first and last levels from the 9-level extended hhgq variable; these levels o correspond to occupied and vacant housing units, respectively, so gq_vect is retaining just the len-7 vector of Group Quarters Facilities unit counts.

Note that the E2E code is rather dated at this point, being several years old. In more up-to-date versions of the code (like the publicly available "Demonstration Data Products" code: https://github.com/uscensusbureau/census2020-das-2010ddp; further updates have also been made internally, but we have not yet made a third public release of code), the schema-handling components of this workflow have changed considerably (mostly to make it somewhat easier to follow the histogram construction process, and easier to extend). Definitions for all schemas can now be found in the schemamaker module (https://github.com/uscensusbureau/census2020-das-2010ddp/blob/master/das_decennial/programs/schema/schemas/schemamaker.py), which builds schemas from products of individual attributes (represented by Python scripts in https://github.com/uscensusbureau/census2020-das-2010ddp/tree/master/das_decennial/programs/schema/attributes).
